---
engines:
  fixme:
    enabled: true
ratings:
  paths: []
exclude_paths: []
languages:
  Ruby: true
  JavaScript: false
  Python: true
  PHP: false
engines:
 radon:
  enabled: true
 shellcheck:
   enabled: true
ratings:
  paths:
    - "**.py"
    - "**.sh"
exclude_paths:
- "images/*"